### ISSUE TITLE
Little bug in the scheme.

### ISSUE THREAD

**Issue by Mikola314** [kestral246/tunnelmaker#1]
https://github.com/kestral246/tunnelmaker/blob/2107669424cc47af465585b46d19a293738099ac/init.lua#L622-L623

There is a typo in the Orthogonal slope up (north reference) scheme.

> [11] = {{{-3, 3},{0,0, 0,  4,4,4,4,  4,40}}, {{-2, 3},{0,0, 0,  4,4,4, 4,  4,**40**}}, ...
replaced by:
> [11] = {{{-3, 3},{0,0, 0,  4,4,4,4,  4,40}}, {{-2, 3},{0,0, 0,  4,4,4, 4,  4,**4**}}, ...

**Comment by kestral246** [comment]
Thanks, Made change in beta branch. Will close after I finish validating water tunnels.

**Comment by kestral246** [comment]
Closing.
