### ISSUE TITLE
Add ability to set length / repetition of tunneling action

### ISSUE THREAD

**Issue by srutzky** [kestral246/tunnelmaker#7]
Currently, tunneling modifies 2 or 3 blocks in a particular direction (at least when using Advanced Trains mode). It would be great if it were possible to set how many dig events should take place with a single right-click. This way someone could tunnel 100 sets of two or so blocks from where they initially clicked.

**Comment by kestral246** [comment]
I want to encourage making tunnels with curves, especially winding curvy ones, so I'll leave long straight tunnels to other mods.
Besides, I've made enough wrong clicks while digging to know that repairing an errant dig with the current design isn't too much work, but repairing with what you propose is not something I want to consider.
